### ISSUE TITLE
LcellId not available using ubxlib on SARA-R422

### ISSUE THREAD

**Issue by johannesmay** [u-blox/ubxlib#124]
Hi again, our tester found an issue where the returned values of ubxlib did not match our expections.

We use `uCellInfoGetCellId()` to read the current cell ID of the modem (after refreshing the parameters of course) and expected the 28 bit LTE cell ID.
`AT+UCGED?` seems to return the exepected value for 2G connections, but returns a "P-CID" instead for LTE connections, which contains different information.

I have some questions about this:
1. Do you think it is intended that `AT+UCGED?` does not return the 28 bit LTE cell ID? The AT command manual mentions it as a parameter in the command documentation as "LcellId", but it's never used by the command.
2. Does it even make sense to call the P-CID a "cell ID"? It seems like the term cell ID is usually associated with the 28 bit identifiers I mentioned above (or the 2G 16 bit identifiers), so returning the P-CID here is a bit confusing to me. The LWM2M resource /4/0/8 (Connectivity Monitoring / Cell ID) is a good example for the use of the term "cell ID" in other places. Maybe it would make sense add some documentation about the actual value the cell ID parameter can contain.
3. How could we access the LcellId? I couldn't find any function in ubxlib to do this. Our modem support contact mentioned that we could use `AT+CEREG?` or `AT+CREG?` to access this value.

Thanks in advance for your help and have a nice weekend :)

**Comment by philwareublox** [comment]
If this is for SARA-R5, could you have a look at +COPS=5 - deepscan. That provides the Cell ID I believe.
uCellNetDeepScan() is something which will be available in the next release.

**Comment by RobMeades** [comment]
Hi Johannes.  When we did cell ID originally, I did think about the ambiguity between physical cell ID and logical cell ID.  I decided, stupidly I have since realized, to stick with one meaning and the meaning I chose was the physical one, probably because my background and the background of those in the office around me is cellular development, where physical cell ID is a useful property of the cell/technology, versus logical cell ID which is a kind of made-up artifact of the network operator.  And to make it worse I didn't document that the cell ID I chose to pass back is the physical one either.

As Phil says, for SARA-R5 there's an `AT+COPS=5` scan, [uCellNetDeepScan()](https://github.com/u-blox/ubxlib/blob/594f4857f909605a48525938a240cd58da4d32fb/cell/api/u_cell_net.h#L547), which I implemented just last week in support of CellTime, and which [returns](https://github.com/u-blox/ubxlib/blob/594f4857f909605a48525938a240cd58da4d32fb/cell/api/u_cell_net.h#L253) both `physicalCellId` and `logicalCellId`, but that won't help you on SARA-R422.

There is definitely a case here for adding new APIs specifically to obtain the logical cell ID and the physical cell ID separately, only problem is that I can't find a "read request" mechanism for it in the SARA-R422 AT manual; it is _mentioned_ as being in the `AT+UCGED` command which we already use to obtain the physical cell ID, but in the description of the command only `P-CID` appears.

That said, your modem support contact is correct that it is emitted on the end of the `+CEREG` URC under the right circumstances and we have some [ridiculously circuitous code for that URC](https://github.com/u-blox/ubxlib/blob/594f4857f909605a48525938a240cd58da4d32fb/cell/src/u_cell_net.c#L432), to cope with all module variants, which currently skips the CI, so we could store it as it flies past, when it is present, with the risk of course that we might miss it [due to the ridiculousness] and end up out of date.  Better than nothing though.

Enough waffling; it _shouldn't_ be difficult to do (barring ridiculousness :-)).  When do you need it by?

**Comment by RobMeades** [comment]
Hi again: I had some spare time this afternoon so find here a [preview branch](https://github.com/u-blox/ubxlib/tree/preview_cell_id_rmea) which replaces [uCellInfoGetCellId()](https://github.com/u-blox/ubxlib/blob/05beedd1b406966e9535663a23d1c3920afb6350/cell/api/u_cell_info.h#L172) with [uCellInfoGetCellIdLogical()](https://github.com/u-blox/ubxlib/blob/preview_cell_id_rmea/cell/api/u_cell_info.h#L172) and [uCellInfoGetCellIdPhysical()](https://github.com/u-blox/ubxlib/blob/05beedd1b406966e9535663a23d1c3920afb6350/cell/api/u_cell_info.h#L182); [uCellInfoGetCellId()](https://github.com/u-blox/ubxlib/blob/05beedd1b406966e9535663a23d1c3920afb6350/cell/api/u_cell_info.h#L172) remains but is marked as deprecated.

I have tested them and they seem to work: please let me know if they are OK for you.  If they are I will merge the change to `master` here and update this issue, then delete the `preview` branch.

**Comment by RobMeades** [comment]
>  I was working on some other stuff over the last couple of days :).

NP.  On the temporary change of `+CEREG` mode thing, it would _probably_ not work for all module types if a `+CEREG` URC happened to land right in the middle of your `AT+CEREG?` query, since the logic to handle the differences in the two formats (URC version versus information response version) is hung off the mode; once in a blue moon of course but just the kind of thing that happens daily in our test system, which I suppose is what it is there for.

Capturing the cell ID as it goes past in the URC _should_ work reliably... famous last words.

Anyway, the change has been approved and passed testing so I will push it here shortly and delete the preview branch, will update this issue when done.

**Comment by RobMeades** [comment]
Now done, see https://github.com/u-blox/ubxlib/commit/fb6e7b01500d4e67d7c33ff17a29dec3d7bca840.  Will close this issue: please feel free to re-open it or start a new one if we need to discuss further.

**Comment by RobMeades** [comment]
@johannesmay: @philwareublox, who is more observant than I, pointed out to me that you said:

> What we did internally while testing is setting AT+CEREG=4 and then use AT+CEREG? to read the values without needing to wait for the URC. Afterwards we reset AT+CEREG=2

...but `ubxlib` [already uses](https://github.com/u-blox/ubxlib/blob/2d66485aca773f1a80872d4e3add0a1d81f73ead/cell/src/u_cell_net.c#L78) `CEREG` mode 4;  `CREG` and `CGREG` it uses mode 2: did you mean those instead? It is extremely confusing, of course, because depending on the way the cellular network you happen to be on happens to be internally connected-up, which registration URC you end up receiving can vary.

**Comment by johannesmay** [comment]
Hm, I didn't run this test myself, my testing colleague ran those commands. Maybe I misunderstood something.

It was just a one-off test anyway, we didn't implement any special logic for this.
