### ISSUE TITLE
Concatenate a string for a message

### ISSUE THREAD

**Issue by alexmaron81** [u-blox/ubxlib#50]
To send a message, I would like to put it together from several parts in advance.
On the one hand I have a file where I saved certain sensor values and on the other hand I would like to add the ICCID and the transmission power of the antenna.

Do you perhaps have an example of how I best concatenate a string?

this is what i use so far
![image](https://user-images.githubusercontent.com/83282470/169967360-51beb312-6b5f-4a7e-b6bb-8d521164c159.png)
![image](https://user-images.githubusercontent.com/83282470/169963930-8c386aef-511d-45cf-98d7-4e61ddd0c9b6.png)
![image](https://user-images.githubusercontent.com/83282470/169967045-4c757439-3b24-49b2-8669-1f29aaa46a7b.png)

**Comment by RobMeades** [comment]
Hi Alex: I see you have `strcat()` in there, commented out, already.  I'd probably use `strncat()` for safety.  Also, note that `uCellInfoGetIccidStr()` returns zero on success, not the number of bytes written to `ICCID_buffer`, so `bytesRead` in the above will likely be 0.

If you have a buffer named `line` that has been populated with a string (i.e. sequence of bytes that includes a null terminating byte) from the file and has room in it for the ICCID as well, and you have `ICCID_buffer` with the ICCID string (i.e. another null-terminated sequence of bytes) in it that represent the ICCID, then you could concatenate those additional bytes into `line` with:

`strncat(line, strlen(ICCID_buffer), sizeof(line) - strlen(line));`

The `sizeof(line) - strlen(line)` is to make sure that you don't overrun the buffer.  You would then MQTT-publish `line` instead of `message`, using `strlen(line)` as the size instead of `sizeof(message)`.

**Comment by alexmaron81** [comment]
Hi Rob: Thanks for the answer!

What has worked very well for me is the following:
that concatenate with "sprintf"
![image](https://user-images.githubusercontent.com/83282470/170941868-545f5b63-a03e-4f9d-b33a-4ec3f527a527.png)

but what if i read a file from which i don't know how big i have to lay out the char array?
I have to be able to change the size of the array dynamically somehow?

**Comment by RobMeades** [comment]
Yes, that works also.  If you don't know the size of the file in advance you have no choice but to read it in chunks rather than reading it all at once.  If you can determine the size at run-then you can [`malloc()`](https://www.programiz.com/c-programming/c-dynamic-memory-allocation) [and don't forget to `free()` afterwards] a chunk of memory of the size you desire.

**Comment by alexmaron81** [comment]
How long can the message be, because I get "Unable to publish our message"

**Comment by alexmaron81** [comment]
![image](https://user-images.githubusercontent.com/83282470/171334407-a469d2ec-e1be-4aa5-839d-a917d1e778ca.png)

**Comment by RobMeades** [comment]
Hi again: there's something strange going on here.  When the code receives a message to be published it first checks if the message is pure ASCII and contains no double-quotes characters.  If it IS pure ASCII and does NOT contain any double-quotes characters then it is most efficient to just send the message as ASCII, otherwise, in the SARA-R412M case, it has to do it in hex mode.

From the log you have pasted above, it seems to be publishing the message as ASCII but the message _does_ contain some double-quotes, which doesn't make any sense.  Let me do some experiments and get back to you.

**Comment by alexmaron81** [comment]
Hi Robot, sending works now and also with the double quotes (this structure is required by the Mqtt server, it is the ICCID)

My problem is currently that I can't send more than four data sets at once.

**Comment by RobMeades** [comment]
OK, the AT manual says:

![image](https://user-images.githubusercontent.com/6726745/172730161-2b871e13-6af2-4768-8274-26b55657b54f.png)

...which suggests that the maximum string length (hex or ASCII) is 256 characters, so if the contents of your payload is good for ASCII then a maximum of 256 bytes applies.  How long, in bytes, does your four data-sets become?

**Comment by alexmaron81** [comment]
the data record that i can send is 235 bytes long.
Is there a way to increase the character length?

**Comment by RobMeades** [comment]
Is what you pasted in above definitely what the code is doing, i.e. the `AT+UMQTTC` command that `ubxlib` sends to the module definitely starts with the numbers `2,2,0,0` and definitely has plain-text in the message part of it and not a hex string (i.e. it has "abc" instead of "616263")?

**Comment by alexmaron81** [comment]
["8988228066602306300",[1654164184000,3,-97,24.1,3.93,4019401,1013,0,0,111],[1654164185000,3,-97,24.1,3.93,4019401,1013,0,0,111],[1654164187000,3,-97,24.1,3.93,4019401,1013,0,0,165],[1654164188000,3,-97,24.1,3.93,4019401,1013,0,0,323]]

**Comment by alexmaron81** [comment]
This is the char string what I am sending

**Comment by RobMeades** [comment]
Apologies, what I meant was, in the trace you pasted in as a picture above, the log line that comes out of `ubxlib` shows a line that begins "AT+UMQTTC": can you confirm what that line looks like when you try to send your string please?

**Comment by alexmaron81** [comment]
This is the output after a successful send ASCII format.

char message[] = "[\"8988228066602306300\",[1654862844000.3,-97,26.0,3.93,4019401,1013,0.0.288],[1654862845000.3,-97.26.0,3.93,4019401.1013 0.0.287],[1654862846000.3,-97.26.0.3.93.4019401.1013.0.0.287],[1654862847000.3,-97.26.0.3.93.4019401.1013.0.0.286]]"

![image](https://user-images.githubusercontent.com/83282470/173061481-3128deb1-9e59-4afd-ad59-d795fd34f9af.png)

**Comment by RobMeades** [comment]
Ah, OK, that's fine, I was just looking at a more recent `ubxlib` code version, not the one you have.

So a message of length 235 bytes long fits within the 256 byte MQTT publish limit; 256 bytes is a limitation of the SARA-R412M-02B module unfortunately, it is not something that `ubxlib` has any influence over.  I understand that you might want to send more in one go but, unfortunately, SARA-R412M is the module with the shortest MQTT message limits of any of our modules.

Sorry!

**Comment by alexmaron81** [comment]
OK. Then the matter is settled.

**Comment by RobMeades** [comment]
Hi again: a discovery - the very latest version of SARA-R412M-02B FW (`M0.12.00,A.02.21`) has an increased MQTT message length (1023 characters)! To obtain the FW, you would need to contact your distributor, or wherever you got your module from, and ask them for the updated FW and the tool to download it to the module; for me to provide it to you, you'd need to have an NDA with u-blox, which I don't think you have.
